def main():
    print("Dungeon Explorer")
    print("Aw, it was so bad we had to censor the whole screen!!!")
    print("A smorgasbord of showgirls and showboys are noticed loligagging nevertheless; one of them starts playing IceJJFish's On the Floor on their smartwatch, while a person interrupts that they're still showering and trying to listen to Lil B's RED FLAME mixtape.")
    print("One of them screams as a robotic centipede with red eyes and large sharp mettalic antennae slithers past.")
    print("A door opens showcasing people dressed in white and assorted bling, as they march in carrying an artifact of sorts.")
    print("A black backgrounded computer beeps revealing green text instructing people.")
    print("A lifeguard reading it runs to the shower for an allegedly drowned; a sumo wrestler takes the place proclaiming to wait until they have done finishing the section.")
    print("Someone says this is how we do it; randomly some other exclaims oh my goodness that thing is so cute; a third says **** YOU DUDE, **** YOU.")
    print("The computer's hardware starts failing due to water damage, stating you don't have to implement the program, you do have to implement the program.   ")   
    print("A portal opens to a city, in which humans in hydraulically-powered mechas thunder forth, speaking of a recent settled war treaty.")
    print("One of them says do you really think you can quit this game think again, showing streams of information to annihilate their injured freewill.")
    print("Some coincidentally young supposedly low dark tetrad people are led to a trick by showpeople their opposite prosing was it just tickles that risibled your cherubic fellowship.")
    print("A boy named Dillon dressed in a middle-length white beard and white contacts dances to raving, insane music.")
    print("After resting, you are woken up by a woman in black & orange colors.")
    print("You walk down some apartment stairs below a sunset sky to find a beach.")
    print("People begin to group in a circle.")
    print("They tell jokes, and begin to enter mechas which are layered.")
    print("The mecha's morals & ethics are discussed, as factions form.")
    print("Everybody calls it a day.")
